### ISSUE TITLE
Reassign ISO codes, Glottocodes and Ethnologue names

### ISSUE THREAD

**Issue by xrotwang** [clld/wals-data#107] opened 2016-06-21 07:54 UTC
Martin has brought to my attention some inconsistencies in WALS links to ISO codes and Glottocodes. The following lists the new ISO codes, Glottocodes, and revised Ethnologue names. In one case, there is also a name change for WALS (Sumu to Mayangna).

| WALS code | Old name | Language name | ISO code | Glottocode | Revised Ethnologue name |
| --- | --- | --- | --- | --- | --- |
| aci |  | Achí | [acr] | achi1256 | Achi |
| pkm |  | Pokomchí | [poh] | poqo1254 | Poqomchi' |
| gam |  | Gamo | [gmv] | gamo1243 | Gamo |
| sum | Sumu | Mayangna | [yan] | maya1285 | Mayangna |
| tzo |  | Tzotzil | [tzo] | tzot1259 | Tzotzil |
| ixi |  | Ixil | [ixl] | ixil1251 | Ixil |
| bem |  | Bemba | [bem] | bemb1257 |  |
| htc |  | Huastec | [hus] | huas1242 | Huastec |
| kyq |  | Kyuquot | [nuk] | nuuc1236 | Nuu-chah-nulth |
| nit |  | Nitinaht | [dtd] | diti1235 | Ditidaht |
| tzu |  | Tzutujil | [tzj] | tzut1248 | Tz'utujil |
| vla |  | Vlaamse Gebarentaal | [vgt] | vlaa1235 | Flemish Sign Language |
| nlr |  | Ngarla | [nrk] | ngar1286 |  |
| nax |  | Naxi | [nxq] | naxi1245 |  |
| akm |  | Arakanese (Marma) | [rmz] | marm1234 | Marma |
| cak |  | Cakchiquel | [cak] | kaqc1270 | Kaqchikel |
| nbk |  | Natügu | [ntu] | natu1246 |  |
| tnn |  | Tunen | [tvu] | tune1261 |  |
| itb |  | Italian (Bologna) | [egl] | emil1241 | Emilian |
| yir |  | Yir Yiront | [yyr] | yiry1247 |  |
| nis |  | Nyishi | [njz] | nyis1236 | Nyishi |
| yug |  | Yugh | [yug] | yugh1239 | Yug |
| ptw |  | Patwin | [pwu] | patw1250 | Patwin |
| win |  | Wintu | [wnw] | wint1259 |  |
| grr |  | Garrwa | [wrk] | gara1269 | Garrwa |
| gla |  | Gelao | [gqu] | qaua1234 | Qau |
| wan |  | Wangkumara | [xwk] | ngur1261 | Wangkumara |
| izi |  | Izi | [izz] | izie1238 | Izii |
| ish |  | Ishkashmi | [isk] | sang1236 | Ishkashmi |
| wor |  | Worora | [wro] | woro1255 | Worrorra |
| mdb |  | Mudburra | [dmw] | mudb1240 | Mudburra |
| mhc |  | Mahican | [xpq] | mohe1244 | Mohegan-Pequot |
| wir |  | Wirangu | [wgu] | wira1265 |  |
| tga |  | Tangga | [hrc] | tang1348 | Niwer Mil |
| lng |  | Lengua | [enx] | leng1262 | Enxet |
| nbd |  | Nubian (Dongolese) | [dgl] | kenu1236 | Andaandi |
| nku |  | Nubian (Kunuz) | [xnz] | kenu1236 | Kenzi (Mattoki) |

**Comment by xflr6** [comment] 2017-10-24 14:27
Here are the same changes as ``(before, after)`` pairs grouped first by WALS code and then by field.
Where ``after`` is set to ``None``, ``before`` is just for information and will not be changed:

https://github.com/clld/wals3/blob/38f316d04f866fe4e1274be4c649227b4671932e/migrations/pending/reassign_iso_codes_glottocodes_and_el_.py#L21-L236

I would like to make sure this is as intended (e.g. when replacing multiple iso codes by one, or when replacing multiple similar Ethnologue names by a new one). Also that all of the ``before`` info should be replaced. Can someone please take a look?

**Comment by xflr6** [comment] 2017-10-26 08:31
Hi @haspelmath, can you maybe [take a look](https://github.com/clld/wals-data/issues/107#issuecomment-339009123)?

**Closed** 2017-11-08 14:52 UTC
